[[configs]]
datasets = ["winogrande", "yelp_polarity", "scitail", "scitail", "paws"]
dataset_config_name = ["en"]
device = "cuda"
learning_rate = 0.3
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
num_epochs = 20
batch_size = 32
peft_type = "attempt"
attn_method = "sub"
temperature = 2087
prompt_init = "embedding_multi"
prompt_init_embedding = "soft_prompts/mnli.bin"
prompt_embedding_paths = ["soft_prompts/mnli.bin", "soft_prompts/qnli.bin", "soft_prompts/qqp.bin", "soft_prompts/record.bin", "soft_prompts/squad.bin", "soft_prompts/sst2.bin"]
prefix_num=6
task_type = "seq_2_seq_lm"
num_virtual_tokens = 50
n_runs = 3
wandb_project = "attempt_multi_experiments"
max_source_length = 256
split_validation_test = true
# max_train_samples = 1000
# max_valid_samples = 500
# max_test_samples = 500
output_dir = "attempt_multi_others"
warmup_steps = 500
shared_attn = true
pad_to_max_length = true