[[configs]]
datasets = ["mnli", "qqp", "multirc", "rte", "cb", "cola"]
dataset_config_name = ["en"]
device = "cuda"
learning_rate = 0.3
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
num_epochs = 20
batch_size = 32
peft_type = "attempt"
attn_method = "sub"
temperature = 2087
prompt_init = "embedding_multi"
prompt_init_embedding = "nlp_soft_prompts/small/mrpc.bin"
prompt_embedding_paths = ["nlp_soft_prompts/small/mrpc.bin", "nlp_soft_prompts/small/rte.bin", "nlp_soft_prompts/small/stsb.bin", "nlp_soft_prompts/small/wnli.bin", "nlp_soft_prompts/small/cb.bin", "nlp_soft_prompts/small/copa.bin", "nlp_soft_prompts/small/wic.bin", "nlp_soft_prompts/small/wsc.bin"]
prefix_num=8
task_type = "seq_2_seq_lm"
num_virtual_tokens = 50
n_runs = 3
wandb_project = "nlp_attempt_small"
max_source_length = 256
split_validation_test = true
# max_train_samples = 1000
# max_valid_samples = 500
# max_test_samples = 500
output_dir = "nlp_attempt_small"
warmup_steps = 500
shared_attn = true
pad_to_max_length = true