[[configs]]
datasets = ["mnli", "qqp", "superglue-multirc", "rte", "superglue-cb", "cola"]
dataset_config_name = ["en"]
device = "cuda"
learning_rate = 0.3
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
num_epochs = 20
batch_size = 32
peft_type = "attempt"
attn_method = "sub"
temperature = 2087
prompt_init = "embedding_multi"
prompt_init_embedding = "nlp_soft_prompts/medium/sst2.bin"
prompt_embedding_paths = ["nlp_soft_prompts/medium/mnli.bin", "nlp_soft_prompts/medium/sst2.bin", "nlp_soft_prompts/medium/qnli.bin", "nlp_soft_prompts/medium/qqp.bin", "nlp_soft_prompts/medium/record.bin", "nlp_soft_prompts/medium/boolq.bin"]
prefix_num=8
task_type = "seq_2_seq_lm"
num_virtual_tokens = 50
n_runs = 3
wandb_project = "nlp_attempt_medium"
max_source_length = 348
split_validation_test = true
# max_train_samples = 1000
# max_valid_samples = 500
# max_test_samples = 500
output_dir = "nlp_attempt_medium"
warmup_steps = 500
shared_attn = true
pad_to_max_length = true