[[configs]]
datasets = ["mnli"]
dataset_config_name = ["en"]
device = "cuda"
learning_rate = 0.3
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
num_epochs = 20
batch_size = 32
peft_type = "prompt_tuning"
prompt_init = "embedding"
prompt_init_embedding = "nlp_soft_prompts/small/spot.bin"
task_type = "seq_2_seq_lm"
num_virtual_tokens = 50
n_runs = 3
wandb_project = "nlp_spot_small"
max_source_length = 256
split_validation_test = true
# max_train_samples = 1000
# max_valid_samples = 500
# max_test_samples = 500
output_dir = "nlp_spot_small"
warmup_steps = 500
shared_attn = false
pad_to_max_length = false
weight_decay = 1e-5

[[configs]]
datasets = ["qqp"]
dataset_config_name = ["en"]
device = "cuda"
learning_rate = 0.3
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
num_epochs = 20
batch_size = 32
peft_type = "prompt_tuning"
prompt_init = "embedding"
prompt_init_embedding = "nlp_soft_prompts/small/spot.bin"
task_type = "seq_2_seq_lm"
num_virtual_tokens = 50
n_runs = 3
wandb_project = "nlp_spot_small"
max_source_length = 256
split_validation_test = true
# max_train_samples = 1000
# max_valid_samples = 500
# max_test_samples = 500
output_dir = "nlp_spot_small"
warmup_steps = 500
shared_attn = false
pad_to_max_length = false
weight_decay = 1e-5

[[configs]]
datasets = ["multirc"]
dataset_config_name = ["en"]
device = "cuda"
learning_rate = 0.3
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
num_epochs = 20
batch_size = 32
peft_type = "prompt_tuning"
prompt_init = "embedding"
prompt_init_embedding = "nlp_soft_prompts/small/spot.bin"
task_type = "seq_2_seq_lm"
num_virtual_tokens = 50
n_runs = 3
wandb_project = "nlp_spot_small"
max_source_length = 348
split_validation_test = true
# max_train_samples = 1000
# max_valid_samples = 500
# max_test_samples = 500
output_dir = "nlp_spot_small"
warmup_steps = 500
shared_attn = false
pad_to_max_length = false
weight_decay = 1e-5

[[configs]]
datasets = ["rte"]
dataset_config_name = ["en"]
device = "cuda"
learning_rate = 0.3
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
num_epochs = 20
batch_size = 32
peft_type = "prompt_tuning"
prompt_init = "embedding"
prompt_init_embedding = "nlp_soft_prompts/small/spot.bin"
task_type = "seq_2_seq_lm"
num_virtual_tokens = 50
n_runs = 3
wandb_project = "nlp_spot_small"
max_source_length = 256
split_validation_test = true
# max_train_samples = 1000
# max_valid_samples = 500
# max_test_samples = 500
output_dir = "nlp_spot_small"
warmup_steps = 500
shared_attn = false
pad_to_max_length = false
weight_decay = 1e-5

[[configs]]
datasets = ["cb"]
dataset_config_name = ["en"]
device = "cuda"
learning_rate = 0.3
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
num_epochs = 20
batch_size = 32
peft_type = "prompt_tuning"
prompt_init = "embedding"
prompt_init_embedding = "nlp_soft_prompts/small/spot.bin"
task_type = "seq_2_seq_lm"
num_virtual_tokens = 50
n_runs = 3
wandb_project = "nlp_spot_small"
max_source_length = 256
split_validation_test = true
# max_train_samples = 1000
# max_valid_samples = 500
# max_test_samples = 500
output_dir = "nlp_spot_small"
warmup_steps = 500
shared_attn = false
pad_to_max_length = false
weight_decay = 1e-5

[[configs]]
datasets = ["cola"]
dataset_config_name = ["en"]
device = "cuda"
learning_rate = 0.3
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
num_epochs = 20
batch_size = 32
peft_type = "prompt_tuning"
prompt_init = "embedding"
prompt_init_embedding = "nlp_soft_prompts/small/spot.bin"
task_type = "seq_2_seq_lm"
num_virtual_tokens = 50
n_runs = 3
wandb_project = "nlp_spot_small"
max_source_length = 256
split_validation_test = true
# max_train_samples = 1000
# max_valid_samples = 500
# max_test_samples = 500
output_dir = "nlp_spot_small"
warmup_steps = 500
shared_attn = false
pad_to_max_length = false
weight_decay = 1e-5